library(readxl)

# Import CSV and Excel files
biblio <- read.csv("data/Billia Croo Meterological Station_a7f32668-ea23-4c80-8bbd-70da675d6667.csv")
adcp <-  read_excel("data/Blue Growth Data Challenge_ADCP 2015.xlsx", sheet = 2)
met <- read_excel("data/Blue Growth Data Challenge_BC Met 2015.xlsx", sheet = 2)
bc_dwr_e_spec <- read_excel("data/Blue Growth Data Challenge_BC-DWR-E specstats 2015.xlsx", sheet = 2)
bc_dwr_h_wave <- read_excel("data/Blue Growth Data Challenge_BC-DWR-H wavestats 2015.xlsx", sheet = 2)
bc_dwr_j_spec <- read_excel("data/Blue Growth Data Challenge_BC-DWR-J specstats 2015.xlsx", sheet = 2)
bc_dwr_j_wave <- read_excel("data/Blue Growth Data Challenge_BC-DWR-J wavestats 2015.xlsx", sheet = 2)
emec_dhi_model_tide <- read_excel("data/Blue Growth Data Challenge_EMEC DHI Model Tide 2015.xlsx", sheet = 2)
fow_met <- read_excel("data/Blue Growth Data Challenge_FoW Met 2015.xlsx", sheet = 2)
sf_dwr_a_spec <- read_excel("data/Blue Growth Data Challenge_SF-DWR-A specstats 2015.xlsx", sheet = 2)
sf_dwr_a_wave <- read_excel("data/Blue Growth Data Challenge_SF-DWR-A wavestats 2015.xlsx", sheet = 2)
eday_meteor_station <- read.csv("data/Eday Meterological Station_e9c17ce2-ca84-41a0-b30a-c1b31095226c.csv")
tidal_current_velocity_east <- read.csv("data/Tidal current and water level model data_ Vertically integrated tidal current flow - velocity vector east component [m_s]_e1c3e4d0-fff2.csv")
tidal_current_velocity_north <- read.csv("data/Tidal current and water level model data_ Vertically integrated tidal current flow - velocity vector north component [m_s]_131092b9-91e.csv")
tidal_current_sea_level <- read.csv("data/Tidal current and water level model data_ Water level elevation, referenced to mean sea level [m]_c92ce4b4-478a-4523-a77f-1.csv")
wave_observations_buoys_spec <- read.csv("data/Wave in-situ observations using Datawell Waverider buoys - Specstats_d52e4c3f-1d0f-4e6c-8b7f-eff9e433651a.csv")
wave_observations_buoys_wave <- read.csv("data/Wave in-situ observations using Datawell Waverider buoys - Wavestats_56907169-2f5d-48e6-a9ce-76bb560cd339.csv")
